### ISSUE TITLE
Administration instructions?

### ISSUE THREAD

**Issue by rbcavanaugh** [aphasia-apps/mainConcept#8]
Should we include administration instructions in the beginning of the app (or somewhere else)? or just link to the manual. @sarahgracedalton @jdrichslp - see if you can comment below and let me know what you think.

**Comment by sghud1** [comment]
I think linking to the manual, or making it a toggle button somewhere would be a good idea, but I don't know that I want to make people click through the administration instructions every time they come back to score (assuming we have some regular/repeat users).
