### ISSUE TITLE
Can we generate a report for clinicians 

### ISSUE THREAD

**Issue by rbcavanaugh** [aphasia-apps/mainConcept#9]
- [x] includes the plot (and each variable)
- [x] Incudes summary statistics
- [x] includes the text output

**Comment by sghud1** [comment]
[] add a citation for the app in the report.
[] add citations for the 3 major MC articles in the report.

**Comment by rbcavanaugh** [comment]
Draft is done. Needs checked

**Comment by rbcavanaugh** [comment]
Closing this issue. SG/JR can brnig up edits
